Run restart handler in serial
paulfantom/ansible-etcd pull request #2
Opened 2018-02-08 14:53 UTC by andymcc

When upgrading versions of etcd3 (for e.g. from the current default to v
3.3.0) the services need to be restarted in serial. This ensures that
the cluster doesn't fail to restart properly.

This can be achieved by delegating to other hosts, from the first host
that calls the handler.

2018-02-08 23:18 UTC, paulfantom requested changes

2018-02-08 23:18 UTC, paulfantom commented on handlers/main.yml
> +    delegate_to: "{{ item }}"
`unsupported parameter for module: delegate_to`
This line has wrong indentation

2018-02-09 08:21 UTC, andymcc commented
Ahh yeah when I moved it from 2.4 supported using ansible_play_hosts to < 2.3 (using groups) i messed up the indent!

2018-02-09 14:40 UTC, paulfantom approved these changes

2018-02-09 14:40 UTC, merged

2018-02-09 14:40 UTC, paulfantom commented
Thanks a lot! :+1: